function [x,y,z] = miura_create_node(i, j, k, a, b, t, eta_A, eta_Z, Tx, Ty, Tz, Norm)

x = NaN;
y = NaN;
z = NaN;

switch mod(j,6)

    case 0
        % j in the set 0, 6, 12, 18, ...
        switch mod(i, 4)
            case 0
                % i in the set 0, 4, 8, 12, ...
                x = (2 * a * j/6) * sin(eta_A/2)...
                    - t * Tx/Norm * k;

                y = floor((i + 1)/2) * b * sin(eta_Z/2)... 
                    + t * Ty/Norm * (4 * floor(i/4) + k);

                z = t * Tz/Norm * k;
            case 1
                % i in the set 1, 5, 9, 13, ...
                x = (2 * a * j/6) * sin(eta_A/2)...
                    + b * cos(eta_Z/2)...
                    - t * Tx/Norm * k;

                y = floor((i + 1)/2) * b * sin(eta_Z/2)... 
                    + t * Ty/Norm * (4 * floor(i/4) + k);

                z = t * Tz/Norm * k;
            case 2
                % i in the set 2, 6, 10, 14, ...
               x = (2 * a * j/6) * sin(eta_A/2)...
                    + b * cos(eta_Z/2)...
                    - t * Tx/Norm * k;

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                    + t * Ty/Norm * (4 * floor(i/4) + (4 - k));

                z = t * Tz/Norm * k;
            case 3
                % i in the set 3, 7, 11, 15, ...
                x = (2 * a * j/6) * sin(eta_A/2)...
                    - t * Tx/Norm * k;

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                    + t * Ty/Norm * (4 * floor(i/4) + (4 -k));

                z = t * Tz/Norm * k;
        end

    case 1
        % j in the set 1, 7, 13, 19, ...
        switch mod(i, 4)
            case 0
                % i in the set 0, 4, 8, 12, ...
                x = (2 * a * (j-1)/6) * sin(eta_A/2)...
                    + (a - t) * sin(eta_A/2)...
                    - t * Tx/Norm * k;

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                    + t * Ty/Norm * (4 * floor(i/4) + k);

                z = (a - t) * cos(eta_A/2) + t * Tz/Norm * k;
            case 1
                % i in the set 1, 5, 9, 13, ...
                x = (2 * a * (j-1)/6) * sin(eta_A/2)...
                    + t * sin(eta_A/2)...
                    + b * cos(eta_Z/2)...                                
                    - t * Tx/Norm * k;

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                    + t * Ty/Norm * (4 * floor(i/4) + k);

                z = t * cos(eta_A/2) + t * Tz/Norm * k;
            case 2
                % i in the set 2, 6, 10, 14, ...
                x = (2 * a * (j-1)/6) * sin(eta_A/2)...
                    + t * sin(eta_A/2)...
                    + b * cos(eta_Z/2)...
                    - t * Tx/Norm * k;

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                    + t * Ty/Norm * (4 * floor(i/4) + (4 -k));

                z = t * cos(eta_A/2) + t * Tz/Norm * k;
            case 3
                % i in the set 3, 7, 11, 15, ...
                x = (2 * a * (j-1)/6) * sin(eta_A/2)...
                    + (a - t) * sin(eta_A/2)...                                
                    - t * Tx/Norm * k;

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                    + t * Ty/Norm * (4 * floor(i/4) + (4 - k));

                z = (a - t) * cos(eta_A/2) + t * Tz/Norm * k;
        end
    
    case 2
        % j in the set 2, 8, 14, 20, ...
        switch mod(i, 4)
            case 0
                % i in the set 0, 4, 8, 12, ...
                x = (2 * a * (j+1)/6) * sin(eta_A/2)...
                    - t * Tx/Norm * k;

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                    + t * Ty/Norm * (4 * floor(i/4) + k);

                z = a * cos(eta_A/2) + t * Tz/Norm * k;
            case 1
                % i in the set 1, 5, 9, 13, ...
                x = (2 * a * (j+1)/6) * sin(eta_A/2)...
                    + b * cos(eta_Z/2)... 
                    - t * Tx/Norm * k;

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                    + t * Ty/Norm * (4 * floor(i/4) + k);

                z = a * cos(eta_A/2) + t * Tz/Norm * k;
            case 2
                % i in the set 2, 6, 10, 14, ...
                x = (2 * a * (j+1)/6) * sin(eta_A/2)...
                    + b * cos(eta_Z/2)... 
                    - t * Tx/Norm * k;

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                    + t * Ty/Norm * (4 * floor(i/4) + (4 - k));

                z = a * cos(eta_A/2) + t * Tz/Norm * k;
            case 3
                % i in the set 3, 7, 11, 15, ...
                x = (2 * a * (j+1)/6) * sin(eta_A/2)...
                    - t * Tx/Norm * k;

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                    + t * Ty/Norm * (4 * floor(i/4) + (4 - k));

                z = a * cos(eta_A/2) + t * Tz/Norm * k;
        end
    
    case 3
        % j in the set 3, 9, 15, 21, 
        switch mod(i, 4)
            case 0
                % i in the set 0, 4, 8, 12, ...
                x = (a * j /3) * sin(eta_A/2) - t * Tx/Norm * (2 - k);

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                    + t * Ty/Norm * ((4 * floor(i/4) + 2) - k);

                z = a * cos(eta_A/2) + t * Tz/Norm * k;
            case 1
                % i in the set 1, 5, 9, 13, ...
                x = (a * j /3) * sin(eta_A/2)...
                    + b * cos(eta_Z/2)...
                    - t * Tx/Norm * (2 - k);

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                    + t * Ty/Norm * ((4 * floor(i/4) + 2) - k);

                z = a * cos(eta_A/2) + t * Tz/Norm * k;
            case 2
                % i in the set 2, 6, 10, 14, ...
                x = (a * j /3) * sin(eta_A/2)...
                    + b * cos(eta_Z/2)...
                    - t * Tx/Norm * (2 - k);

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                     + t * Ty/Norm * ((4 * floor(i/4) + 2) + k);

                z = a * cos(eta_A/2) + t * Tz/Norm * k;
            case 3
                % i in the set 3, 7, 11, 15, ...
                x = (a * j /3) * sin(eta_A/2)...
                    - t * Tx/Norm * (2 - k);

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                     + t * Ty/Norm * ((4 * floor(i/4) + 2) + k);

                z = a * cos(eta_A/2) + t * Tz/Norm * k;
        end

    case 4
        % j in the set 4, 10, 16, 22, ...
        switch mod(i, 4)
            case 0
                % i in the set 0, 4, 8, 12, ...
                x = (a * (j - 1) /3) * sin(eta_A/2)...
                    + (a - t) * sin(eta_A/2)...
                    - t * Tx/Norm * (2 - k);

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                    + t * Ty/Norm * ((4 * floor(i/4) + 2) - k);

                z = a * cos(eta_A/2)...
                    - (a - t)*cos(eta_A/2)...
                    + t * Tz/Norm * k;
            case 1
                % i in the set 1, 5, 9, 13, ...
                x = (a * (j - 1) /3) * sin(eta_A/2)...
                    + t * sin(eta_A/2)...
                    + b * cos(eta_Z/2)...
                    - t * Tx/Norm * (2 - k);

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                    + t * Ty/Norm * ((4 * floor(i/4) + 2) - k);

                z = a * cos(eta_A/2)...
                    - t*cos(eta_A/2)...
                    + t * Tz/Norm * k;
            case 2
                % i in the set 2, 6, 10, 14, ...
                x = (a * (j - 1) /3) * sin(eta_A/2)...
                    + t * sin(eta_A/2)...
                    + b * cos(eta_Z/2)...
                    - t * Tx/Norm * (2 - k);

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                    + t * Ty/Norm * ((4 * floor(i/4) + 2) + k);

                z = a * cos(eta_A/2)...
                    - t*cos(eta_A/2)...
                    + t * Tz/Norm * k;
            case 3
                % i in the set 3, 7, 11, 15, ...
                x = (a * (j - 1) /3) * sin(eta_A/2)...
                    + (a-t) * sin(eta_A/2)...
                    - t * Tx/Norm * (2 - k);

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                    + t * Ty/Norm * ((4 * floor(i/4) + 2) + k);

                z = a * cos(eta_A/2)...
                    - (a - t)*cos(eta_A/2)...
                    + t * Tz/Norm * k;
        end
    
    case 5
        % j in the set 5, 11, 17, 23, ...
        switch mod(i, 4)
            case 0
                % i in the set 0, 4, 8, 12, ...
                x = (2 * a * (j + 1) /6) * sin(eta_A/2)...
                    - t * Tx/Norm * (2 - k);

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                    + t * Ty/Norm * ((4 * floor(i/4) + 2) - k);

                z = t * Tz/Norm * k;
            case 1
                % i in the set 1, 5, 9, 13, ...
                x = (2 * a * (j + 1) /6) * sin(eta_A/2)...
                    + b * cos(eta_Z/2)...
                    - t * Tx/Norm * (2 - k);

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                    + t * Ty/Norm * ((4 * floor(i/4) + 2) - k);

                z = t * Tz/Norm * k;
            case 2
                % i in the set 2, 6, 10, 14, ...
                x = (2 * a * (j + 1) /6) * sin(eta_A/2)...
                    + b * cos(eta_Z/2)...
                    - t * Tx/Norm * (2 - k);

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                    + t * Ty/Norm * ((4 * floor(i/4) + 2) + k);

                z = t * Tz/Norm * k;
            case 3
                % i in the set 3, 7, 11, 15, ...
                x = (2 * a * (j + 1) /6) * sin(eta_A/2)...
                    - t * Tx/Norm * (2 - k);

                y = floor((i + 1)/2) * b * sin(eta_Z/2)...
                    + t * Ty/Norm * ((4 * floor(i/4) + 2) + k);

                z = t * Tz/Norm * k;
        end

end

