#import "../template.typ": *


#box(
  fill: aqua.darken(10%),
  width: 100%,
  inset: (x: 10pt),
  outset: (y: 5pt),
  [= Appendix A: Thick Origami Kinematic Derivation],
)

Each crease in the Miura-Ori geometry can be modelled as a revolute hinge, with Denavit-Hartenberg (DH) matrices allowing for transfromation between the coordinate system of one hinge to the other. A general DH matrix as well as an inverse DH matrix are shown in *@A-dh_matrix* and *@A-inverse-dh_matrix* respectively.

$
  T_((i+1)i) =mat(
    cos theta_i, -cos beta_(i(i+1)) sin theta_i, sin beta_(i(i+1)) sin theta_i, a_(i(i+1)) cos theta_i;
    sin theta_i, cos beta_(i(i+1)) sin theta_i, -sin beta_(i(i+1)) sin theta_i, a_(i(i+1)) sin theta_i;
    0, sin beta_(i(i+1)), cos beta_(i(i+1)), R_i;
    0, 0, 0, 1
  )_(4 times 4)
$<A-dh_matrix>

$
  T_(i(i+1)) = T_((i+1)i)^(-1) =mat(
    cos theta_i, sin theta_i, 0, -a_(i(i+1));
    -cos beta_(i(i+1)) sin theta_i, cos beta_(i(i+1)) cos theta_i, sin beta_(i(i+1)), - R_i sin beta_(i(i+1));
    sin beta_(i(i+1)) sin theta_i, -sin beta_(i(i+1)) cos theta_i, cos beta_(i(i+1)), - R_i cos beta_(i(i+1));
    0, 0, 0, 1
  )_(4 times 4)
$<A-inverse-dh_matrix>

For thin panel origami architectures $R = 0$ and $a = 0$ allowing for *@A-dh_matrix* and *@A-inverse-dh_matrix* to be reduced to $3 times 3$ matrices. For thick panel origami however, $a eq.not 0$ and the resulting linkage is a bennet linkage. The closure condition however remains the same as the thin panel configuration and is shown in *@A-closure-condition*.

$
  [T_(2 -> 1)]_(4 times 4) [T_(3 -> 2)]_(4 times 4) [T_(4 -> 3)]_(4 times 4) = [T_(4 -> 1)]_(4 times 4)
$<A-closure-condition>

The transformation matrices can be simplified further by  applying the constraints of the Miura-Ori geometry shown in *@2-thick-origami-substitutions*. Utilizing these conditions, the simplifying substitutions shown in *@A-subs* will be made into the transformation matrices.

$
  beta_34 = pi - beta_12 quad beta_41 = pi - beta_23
  \ a_34 = a_12 = a_23 sin(beta_12)/sin(beta_23) = a_41 sin(beta_12)/sin(beta_23)
  \
$<A-subs>

The resulting transformation matrices for each revolute hinge is shown in *@A-mat-1-2*, *@A-mat-3-2*, *@A-mat-4-3* and *@A-mat-4-1*, with *@A-mat-4-1* being the inverse matrix utilizing the form shown in *@A-inverse-dh_matrix*.

$
  [T_(2 -> 1)]_(4 times 4) = mat(
    cos(theta_1), -cos(beta_12) sin(theta_1), sin(beta_12) sin(theta_1), (a_23 sin(beta_12) cos(theta_1))/(csc(beta_23) );
    sin(theta_1), cos(beta_12) cos(theta_1), -sin(beta_12) cos(theta_1), (a_23 sin(beta_12) sin(theta_1))/csc(beta_23);
    0, sin(beta_12), cos(beta_12), 0;
    0, 0, 0, 1;
  )_(4 times 4)
$<A-mat-1-2>

$
  [T_(3 -> 2)]_(4 times 4) = mat(
    cos(theta_2), -cos(beta_23) sin(theta_2), sin(beta_23) sin(theta_2), a_23 cos(theta_2);
    sin(theta_2), cos(beta_23) cos(theta_2), -sin(beta_23) cos(theta_2), a_23 sin(theta_2);
    0, sin(beta_23), cos(beta_23), 0;
    0, 0, 0, 1;
  )_(4 times 4)
$<A-mat-3-2>

$
  [T_(4 -> 3)]_(4 times 4) = mat(
    cos(theta_3), cos(beta_12) sin(theta_3), sin(beta_12) sin(theta_3), (a_23 sin(beta_12)cos(theta_3))/sin(beta_23);
    sin(theta_3), -cos(beta_12) cos(theta_3), -sin(beta_12) cos(theta_3), (a_23 sin(beta_12) sin(theta_3))/(sin(beta_23) );
    0, sin(beta_12), -cos(beta_12), 0;
    0, 0, 0, 1;
  )_(4 times 4)
$<A-mat-4-3>

$
  [T_(4 -> 1)]_(4 times 4) = mat(
    cos(theta_4), sin(theta_4), 0, -a_23;
    cos(beta_23) sin(theta_4), -cos(beta_23) cos(theta_4), sin(beta_23), 0;
    sin(beta_23) sin(theta_4), -sin(beta_23) cos(theta_4), -cos(beta_23), 0;
    0, 0, 0, 1;
  )_(4 times 4)
$<A-mat-4-1>

Substituting these four transformation matrices (*@A-mat-1-2*, *@A-mat-3-2*, *@A-mat-4-3* and *@A-mat-4-1*,) into the closure condition (*@A-closure-condition*) yields 16 equations. These 16 equations can be assigned an index depending on which parameter in each matrix the equation links to, for example Eq (4,2) corresponds to the equation generated by the terms in the 4th row and second column of each matrix.

Using this index, equations Eq (4,1), Eq (4,2), Eq (4,3) and Eq (4,4) are all trivial equations (either $0=0$ or $1=1$). The equations generated by the top left nine terms of each matrix Eq (1,1) to Eq (3,3) match the equations generated by the spherical linkage for thin panel origami architectures. The remaining three equations (Eq (1,4), Eq (2,4) and Eq (3,4)) contain thickness terms ($a$) within them, these equations are shown in *@A-eq-1-4*, *@A-eq-2-4* and *@A-eq-3-4*.

Eq (1,4)
$
  A = cos(theta_1) cos(theta_2) - cos(beta_12) sin(theta_1) sin(theta_2)
  \
  B = -cos(beta_12) cos(beta_23) sin(theta_1) cos(theta_2)... \ ...
  + sin(beta_12) sin(beta_23) sin(theta_1)
  - cos(beta_23) cos(theta_1) sin(theta_2)
  \ \
  a_23 (
    (A sin(beta_12) cos(theta_3))/sin(beta_23)
    +
    (B sin(beta_12) sin(theta_3))/ sin(beta_23)
    +
    (sin(beta_12) cos(theta_1))/sin(beta_23)
    +
    A
  )
  =
  -a_23
$<A-eq-1-4>

Eq (2,4)
$
  C = cos(theta_2) sin(theta_1) + cos(beta_12) cos(theta_1) sin(theta_2)
  \
  D = cos(beta_12) cos(beta_23) cos(theta_1) cos(theta_2)... \ ...
  - cos(theta_1) sin(beta_12) sin(beta_23)
  - cos(beta_23) sin(theta_1) sin(theta_2)
  \ \
  a_23 (
    (C sin(beta_12) cos(theta_3))/sin(beta_23)
    +
    (D sin(beta_12) sin(theta_3))/sin(beta_23)
    +
    (sin(beta_12) sin(theta_1))/sin(beta_23)
    +
    C
  )
  =
  0
$<A-eq-2-4>

Eq (3,4)
$
  E = sin(beta_12) cos(beta_23) cos(theta_2) + cos(beta_12) sin(beta_23)
  \ \
  a_23((sin^2 (beta_12) sin(theta_2) cos
    (theta_3))/(sin(beta_23))
    + (E sin(beta_12) sin
    (theta_3))/sin(beta_23)
    + sin
    (beta_12) sin(theta_2)) = 0
$<A-eq-3-4>

In these three equations an $a_23$ term can be factored out, and given that $a_23 eq.not 0$ which is true for thick panel origami it can be removed from each equation. This implies that panel thickness has no impact on the kinematics of the origami structure. The remaining nine non-trivial equations (Eq (1,1) to Eq (3,3)) can then be manipulated using trigonometric identities *@dataset* to yield the four kinematic relationships shown in *@2-kinematic-relationship-equations*.

