#include "../template.typ"

To mitigate the issues with the gap present in the first iteration, an alternative unit panel geometry was chosen. After consulting with the team and conducting further research the geometry shown in *@2-thick-panel-geometry* was chosen to base the computational model around. This geometry utilises an axis shift method to ensure that the thick panel geometry can be folded without creating a gap *@offset_geometry*. It was observed that each side of the panel formed an L shape and that along each straight line, the geometry itself could be modelled as a series of alternating L shaped panels. These panels could later be converted into a three dimensional structure by connecting the segments of the panels in parallel lines together with faces.

#figure(
  image("../images/2_offset_thickness.png", width: 80%),
  caption: [Image depicting the thick panel geometry chosen for the final kinematic model throughout the folding behaviour.],
  supplement: [Figure],
  kind: figure,
)<2-thick-panel-geometry>

To create a ruleset to generate the coordinates of the tessellated structure, a similar panel-centric coordinate system depicted in *@2-model-1-coords* was applied to this geometry. This $i,j,k$ coordinate system is shown in *@2-thick-panel-coord-system*.

#figure(
  image("../images/2_thic_panel_coord_system.png", width: 60%),
  caption: [Image depicting the $i,j,k$ coordinate system applied to the thick panel geometry chosen for the final kinematic model.],
  supplement: [Figure],
  kind: figure,
)<2-thick-panel-coord-system>

Utilizing the unit vectors defined in *@2-unit-vectors* and *@2-orthogonal-unit-vectors* as well as the coordinate system shown in *@2-thick-panel-coord-system*, each coordinate within the geometry could be described in terms of a series of unit vectors, multiplied by a length and added or subtracted from one another. To visualize the algebraic equations generated from such formulas, Wolfram Mathematica was utilized, an example block of code to model the coordinates depicted in *@2-thick-panel-coord-system* is shown in *@2-wolfram-code*.


#figure(
  image("../images/2-example-wolfram-code.png", width: 100%),
  caption: [Image depicting an example block of Wolfram Mathematica code for the geometry shown in  *@2-thick-panel-coord-system*.],
  supplement: [Figure],
  kind: figure,
)<2-wolfram-code>

After varying $i,j$ and $k$ and observing patterns in the algebraic expressions outputted for each coordinate the following key deductions were noted:

- *Invalid and Repeated Coordinate Combinations*:Not all combinations of $i,j$ and $k$ yield a valid point, as shown in *@2-thick-panel-coord-system* some points lie outside of the geometry or lie on a crease where the coordinate is repeated. To implement this into the kinematic simulation, and to simplify the coordinate generation rule set it was decided that each input of $i,j$ and $k$ would first be validated before its cartesian coordinates were computed.

- *Repeating Expressions in the $j$ Direction*: Due to the coordinate system chosen for the geometry, the $j$ coordinate index would see a repeating pattern in terms of the algebraic expressions generated every six points. To implement this pattern into the model, modular logic would be use to develop a j index normalised by six.

- *Repeating Expressions in the $i$ Direction*: Similarly to the $j$ direction, the $i$ coordinate index would see a repeating pattern every four points. This would also influence the modular logic of the final simulation.

- *Maximum Ranges for $i$, $j$ and $k$*: Due to the coordinate system chosen for this geometry, the indeces were found to vary as $k in {0,1,2}$; $i = 0,1,...,i_"max"$ and $j = 0,1,...,j_"max"$ where $i_"max"$ and $j_"max"$ are shown in *@2-i-max* and *@2-j-max* respectively where $Y_"Panels"$ and $X_"Panels"$ describe the number of panels in a given axes. .

$
  i_"max" = 2 Y_"Panels" - 1
$<2-i-max>
$
  j_"max" = 3 X_"Panels" - 1
$<2-j-max>

Utilizing the deductions above as well as carefully inspecting the algebraic equations generated by the Wolfram Mathematica code, a coordinate validation ruleset (shown in its entirety in *Appendix B*) and a coordinate generation ruleset (shown in its entirety in *Appendix C*) were created.
